Finished pgSQL Build, Dummy Data
Cyberskout99/PandApp pull request #12
Opened 2018-12-06 08:21 UTC by Cyberskout99

Contains SQL script written for postgreSQL.  Zipped folder contains numerous CSV files that can be read into the Db.

Please note all tables are written to delete/recompile after each re-start of the Db.  We will want to remove this functionality once the app is closer to production. Foreign keys will need to be revisited as well.

2018-12-10 15:24 UTC, aaronvbrown requested changes
We'll need to replace FROM 'C:\Users\Paul\Desktop\SQL Files\' with references for this to work on anyone's machine but Paul's.  Please correct me if I'm wrong!

2018-12-11 22:21 UTC, gittyeric commented on PDXwildlifeDb.sql
> +FROM 'C:\Users\Paul\Desktop\SQL Files\Inf_tbl.csv' DELIMITER ',' CSV HEADER;
As Aaron mentioned, we can refactor this a bit to work on everyone's machines.  You'll need to add the csv files to the project itself (in some common-sense folder off the root, let's call it X).  Then you can use the 'relative' directory of './' to reference those csv files.  For example, C:\Users\Paul\Desktop\Inf_tbl.csv becomes './X/Inf_tbl.csv'.  As long as you then run the sql from the root of the folder, everything should work.

2018-12-12 00:55 UTC, Cyberskout99 commented
Okay - I've edited the syntax in the SQL file I submitted before.  Take a look now, and please let me know if any follow-up is required.

Thanks,
Paul

2018-12-13 02:58 UTC, aaronvbrown approved these changes
Let's try it out.  Thanks, Paul!

2018-12-13 02:58 UTC, merged